### ISSUE TITLE
Possible typo in the video chapter

### ISSUE THREAD

**Issue by brenc** [savonet/book#1]
I'm nearly finished with the book. It's been super helpful. My mind is blown at all the cool stuff I didn't even know I could do.

I noticed quite a few typos, incorrect examples, etc. For example, I believe there is a typo in this section of the video chapter:

`Another useful parameter is the gop (group of picture) which can be set by passing the
argument g and controls how often keyframes are inserted (we insert one keyframe every
g frames). A typical default value is 12, which allows easy seeking in videos, but for video
streams this value can be increased in order to decrease the size of the video. The habit for
streaming is to have a keyframe every 2 minutes or less, which means setting g=50 at most
for the default framerate of 25 images per second.`

Shouldn't that read `2 seconds or less`?

Should I report the other typos and such here as individual tickets? If the sources were made available I could probably help edit the book directly as well.

**Comment by smimram** [comment]
Thanks for your feedback! It is of course 2 *seconds*. This is now corrected and will be part of the next update of the book.

Please keep on posting whichever problem you see here (be it small typos), this is always very helpful. You can put them all in one BR if this is easier for you!
