### ISSUE TITLE
Epub version broken

### ISSUE THREAD

**Issue by Moonbase59** [savonet/book#8]
How to check if I have the latest `.epub` version of the book? How is it integrated in the Liquidsoap CI? There are no releases here except a very old one.

I cannot check the version for downloading at http://www.liquidsoap.info/book/book.epub for actuality because it has no version, and the string to search for (see https://github.com/savonet/book/discussions/7#discussioncomment-6537013) is empty.

The current version of ebook doesn’t open with
- Calibre E-book viewer
- Foliate

Only
- Thorium
shows at least a bit.

The version I downloaded a few months back did work.

![The Liquidsoap book  EPUB  — E-book viewer_003](https://github.com/savonet/book/assets/3706922/b11e227f-f475-4f5c-81ab-26b00a2b380f)  
_Calibre E-book viewer_

![The Liquidsoap book_002](https://github.com/savonet/book/assets/3706922/ea9bda11-0e44-4b4b-860f-dc2b8a7e3523)  
_Foliate_

![Thorium - The Liquidsoap book_001](https://github.com/savonet/book/assets/3706922/3b8f690d-49ec-45b8-93a8-ed86bded188e)  
_Thorium, at least shows there is no "compilation date"_

**Comment by smimram** [comment]
I have just added the compilation date on the epub. However, the current one opens cleanly on foliate here...

**Comment by Moonbase59** [comment]
Thanks! But something really, really odd here: Calbre’s Ebook Viewer and Foliate can’t open it (still idling after 10 minutes), although these work fine with all other ebooks.

The only program I could make opening it was Thorium.

![Arbeitsfläche 1_034](https://github.com/savonet/book/assets/3706922/10c203bd-c9a1-4af4-ab4d-e98858e91481)

![Thorium - The Liquidsoap book_002](https://github.com/savonet/book/assets/3706922/934589c4-bb2e-41aa-a935-591f9fcafcd0)

Still, if I may, a bad idea to hide the verion somewhere in the bokk. I really always have to check up Github, find this closed issue and look up the wording "The version you are holding…", just to then search the book for this text. _Only to find if I got the current one._

Nevertheless, thanks for keeping this up and current. Hope we can find the bug.

**Comment by smimram** [comment]
That's strange, at least foliate is fine here:
![image](https://github.com/savonet/book/assets/2012073/cfabdf95-d7d8-4b25-8b94-b6e83ca6a9f6)
I'll try to make the version more visible soon

**Comment by Moonbase59** [comment]
Wonderful, looking forward to that, and many thanks for all your work!
